### PR TITLE
Make email name id configurable

### PR DESCRIPTION
**Pull request by joelharkes**
We were using a key cloak/aws cognito setup connected with SAML2, we had the problem that we had to change the name ID o f the application code.

We had to change the name ID. this would allow us not to keep a fork of your package, I would love to have this merged :)

### CODE REVIEW

**Comment by joelharkes** [comment]
@upwebdesign  can you look at this PR? 🙇

**Comment by upwebdesign** [comment]
@joelharkes this looks good to me. You have tested it yourself and know it works?

**Comment by joelharkes** [comment]
Yes we replaced it with `NAME_ID_FORMAT_PERSISTENT` which worked for us.

**Comment by joelharkes** [comment]
@upwebdesign  can you merge it?

**Comment by upwebdesign** [comment]
@joelharkes done.

**Pull request merged**
