### PR TITLE
allow loading a sp certificate from path

### PR DESCRIPTION
**Pull request by as-dialoggroup**
Pull request  #89 

It seems my IDE messed up the whitespaces at some points. It's the default setting for the projects in our company.
Hope this is not an issue.

### CODE REVIEW

**Comment by upwebdesign** [comment]
@as-dialoggroup this looks very simple and effective. You have tested this, correct? If so, I would like to get this merged in.

**Comment by upwebdesign** [comment]
@as-dialoggroup also, it seems the README should also be updated to describe how this should be used, would you please update the appropriate section of the README with some examples perhaps? Thank you for your contribution!

**Comment by chindit** [comment]
Why not using the same as for metadata ?

`$cert = Storage::disk('samlidp')->get(config('samlidp.certname', 'cert.pem'));`  (MetadataController.php:22)

**Comment by JaZo** [comment]
> Why not using the same as for metadata ?

That would be awesome! We use this package in one of our projects and are migrating to Kubernetes hosting. In our scenario it's easier to load secrets from ENV rather than files. I'll get a PR ready for that!

**Comment by as-dialoggroup** [comment]
- tested
- merged
- updated readme
- tested again

> Why not using the same as for metadata ?
> $cert = Storage::disk('samlidp')->get(config('samlidp.certname', 'cert.pem')); (MetadataController.php:22)

Wouldn't that be a breaking change? That way, setting the certificate as a string is not possible anymore.

**Comment by JaZo** [comment]
@as-dialoggroup, I've implemented that in a non-breaking way: #95

**Comment by JaZo** [comment]
@Treggats, I also like to get these changes through! Maybe you can help test my PR and leave a review? We're currently using my fork/PR in production and it's running smooth for months now.

**Comment by Treggats** [comment]
@JaZo I just deployed it to a dev environment. With one addition, Laravel Vapor/Lambda doesn't seem to like the xml opening tag. With that removed it works like a charm.

**Comment by Treggats** [comment]
While the code looks good, I can't test it as it still requires a file. Which isn't possible on Laravel Vapor/Lambda.

**Review by Treggats — APPROVED** [review]

**Comment by upwebdesign** [comment]
@Treggats @JaZo @as-dialoggroup ,

This is some nice dialog, great job. Sorry I have not contributed to the conversation up to this point. I want to get this released to a new version. However, I am unclear whether or not this is a breaking change. I am also not currently active in using this package, so time would be an issue to get this adequately tested. I would rely on you to determine if this can be merged and released. If it is clear to release, please confirm. Thanks!

**Comment by Treggats** [comment]
@upwebdesign Sidenote regarding #95 @JaZo mentioned that he has that running in production for quite some time now. I've tested it on my side as well and seems to work well

**Comment by upwebdesign** [comment]
@Treggats, so if I'm understanding correctly, both PR's could be merged in and this would provide you with the functionality you are looking for.

**Comment by Treggats** [comment]
@upwebdesign looking good. Works locally with our testsuite 👌

**Comment by JaZo** [comment]
We don't need this particular fix for our app, but I've also tested it and can confirm it's backwards compatible. Would be nice if we can get this and #95 merged and released! 🚀

**Review by JaZo — APPROVED** [review]

**Review by SanderMuller — APPROVED** [review]

**Pull request merged**
